### ISSUE TITLE
Test version with classic - plugin version 0.0.9

### ISSUE THREAD

**Issue by ekkichdanskespil** [danskespil/gradle-plugin-release#2]
Same test as for classic plugin 0.0.5 (which worked) but with classic plugin version 0.0.9.

Evaluating project ':xxx' using build file 'C:\git\xxxxx\xxx\build.gradle'.
Skipping rebuild strategy because clean is false, "release." properties are true and head version is 0.0.57
Skipping development strategy because stage (final) is not one of: [dev]
Skipping pre-release strategy because stage (final) is not one of: [milestone, rc]
Skipping final strategy because repo is dirty.
Skipping snapshot strategy because stage (final) is not one of: [SNAPSHOT]
Skipping snapshot default strategy because stage (final) is not one of: [SNAPSHOT]
LifecyclePlugin No [release] task. Adding it
LifecyclePlugin No [polish] task. Adding it
LifecyclePlugin Added [release] dependsOn [build]
LifecyclePlugin Added [release] dependsOn [publish]
LifecyclePlugin At this point, there is no task [publish] so it makes no sense to add a depency to [artifactoryPublish] to it. Skipping
LifecyclePlugin At this point, there is no task [check] so it makes no sense to add a depency to [integrationTest] to it. Skipping
LifecyclePlugin At this point, there is no task [polish] so it makes no sense to add a depency to [sonarqube] to it. Skipping
Skipping rebuild strategy because clean is false, "release." properties are true and head version is 0.0.57
Skipping development strategy because stage (final) is not one of: [dev]
Skipping pre-release strategy because stage (final) is not one of: [milestone, rc]
Skipping final strategy because repo is dirty.
Skipping snapshot strategy because stage (final) is not one of: [SNAPSHOT]
Skipping snapshot default strategy because stage (final) is not one of: [SNAPSHOT]
Project evaluation failed including an error in afterEvaluate {}.
org.gradle.api.GradleException: No version strategies were selected. Run build with --info for more detail.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
...

**Comment by ekkichdanskespil** [comment]
Something to do with the following command changed from "ReleaseClassicPlugin.groovy'" to "ReleaseBranchPlugin.groovy'" in build.gradle?

def thisPlugin = engine.loadScriptByName('dk/danskespil/gradle/plugins/release/ReleaseBranchPlugin.groovy')

**Comment by ekkichdanskespil** [comment]
Doh. Have to commit all changes before release. Works also with version 0.0.9. Closing issue.
